@isTest 
private class ControllerForConfirmEstimatedUsage_Test{
    private testmethod static void test(){
        /*Account acc = [select id from Account where isPersonAccount = true limit 1];
        Contact cont = [select id from Contact where accountID = :acc.ID limit 1];
        User oUser = [select contactId from User where contactId =: cont.ID limit 1];
         /*
        String searchESID = 'sic12345';
        Premises__c premise = new Premises__c (ESID__c = searchESID);
        insert premise;
        
        AccountPremiseAssociation__c apa = new AccountPremiseAssociation__c(Premise__c = premise.ID,account__c = acc.ID);
        insert apa;
        

        
        user oUser=TrueCostTestUtilities.createTestAccountContactUserPremiseAPA(); 
        
           
        System.Runas(oUser){
            ControllerForConfirmEstimatedUsage controller = new ControllerForConfirmEstimatedUsage();
           // //controller.MakeTheEstimate();
           //// controller.getmulistdata();
            //controller.getchartdata();
            //controller.mulist = new list<monthly_usage__c>{new monthly_usage__c(month_number__C = 1, usage__c = 10.0,premise__c = premise.ID)};
           //// controller.ShopWithEstimateUsage();
           //// controller.RaiseEstimate();
           //// controller.LowerEstimate();
            
        }
        */ 
    }
}