public with sharing class FQPosition {

	public datetime Contract_Month {get;set;}
	public decimal margin {get;set;}
	public decimal Customer_Requirements {get;set;}
	public decimal Temp_BL {get;set;}
	public decimal Temp_NL {get;set;}
	public decimal targetVolume {get;set;}
	public decimal Volume {get;set;}
	public decimal FuelPercentage {get;set;}
	public decimal Fuel {get;set;}
	public decimal Swing_Cost {get;set;}
	public decimal Adder {get;set;}
	public decimal Total_Cost {get;set;}
	public decimal Customer_Price {get;set;}
	public decimal storageAffectedVolume {get;set;}
	public decimal DT_NYMEX {get;set;}
	public decimal consultantMargin {get;set;}
	public decimal marginCES {get;set;}
	public decimal DT_Basis_Physical {get;set;}
	public decimal Balancing {get;set;}
	public decimal Swing100 {get;set;}
	public decimal Other_Charges {get;set;}
	public decimal DT_Basis {get;set;}
	public decimal Pommodity {get;set;}
	public decimal PL_Demand {get;set;}
	public decimal Last12 {get;set;}
	public decimal Historical {get;set;}
	public decimal Weatherized_Volume {get;set;}

	public FQPosition() {
		
	}
}