@isTest
private class MyAccount_Test {

 
	static testmethod void testMyAccount(){
		/*user oUser = TrueCostTestUtilities.createTestAccountContactUserPremiseAPA();
		System.runAs(oUser) {
			PageReference pageRef=page.myaccount;
			test.setCurrentPageReference(pageref);
   	     	MyAccount TheController= new MyAccount();
   	     	//thecontroller.getcurrentplanstars();
   	     	//thecontroller.rateyourrep();  commented out because it would only work if test user had an order!
   	     	//thecontroller.getrecentreviews();
   	     	thecontroller.its1();
   	     	thecontroller.its2();
   	     	thecontroller.its3();
   	     	thecontroller.its4();
   	     	thecontroller.its5();
   	     	//thecontroller.saverating();
   	     	
   	     	thecontroller.getInvitecount();
   	     	//thecontroller.grantmeterdatapermission();
   	     	
   	     	thecontroller.navtoinvite();
		}
	*/	
	}
}