@isTest

public class repeaterTest {
	
 public static testMethod void t1() {  
repeatTest tst = new repeatTest();
tst.runit();
}
 public static testMethod void t2() {  
repeatTest2 tst = new repeatTest2();
tst.runit();
}

 public static testMethod void t3() {  
repeatTest3 tst = new repeatTest3();
tst.runtit();
}

 public static testMethod void t4() {  
repeatTest4 tst = new repeatTest4();
tst.runtit();
}

 public static testMethod void t5() {  
repeatTest5 tst = new repeatTest5();
tst.runtit();
}
 public static testMethod void t6() {  
repeatTest6 tst = new repeatTest6();
tst.runtit();
}
 public static testMethod void t7() {  
repeatTest7 tst = new repeatTest7();
tst.runtit();
}

 public static testMethod void t8() {  
repeatTest8 tst = new repeatTest8();
tst.runtit();
}
    public static testMethod void t9() {  
    repeatTest9 tst = new repeatTest9();
    tst.runtit();
}
    
}